-- MySQL Script generated by MySQL Workbench
-- Wed Aug 15 15:54:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reverse_auction
-- -----------------------------------------------------
-- Database  for Reverse Auctioner
DROP SCHEMA IF EXISTS `reverse_auction`;

-- -----------------------------------------------------
-- Schema reverse_auction
--
-- Database  for Reverse Auctioner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reverse_auction`
  DEFAULT CHARACTER SET utf8mb4;
USE `reverse_auction`;

-- -----------------------------------------------------
-- Table `reverse_auction`.`UserRole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`UserRole`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`UserRole` (
  `idUserRole`   INT         NOT NULL,
  `userRoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUserRole`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reverse_auction`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`User`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`User` (
  `idUser`        INT          NOT NULL AUTO_INCREMENT,
  `userLogin`     VARCHAR(30)  NOT NULL,
  `userFirstName` VARCHAR(45)  NOT NULL,
  `userLastName`  VARCHAR(45)  NOT NULL,
  `userBirth`     DATE         NULL,
  `userMail`      VARCHAR(100) NOT NULL,
  `userRoleId`    INT          NOT NULL DEFAULT 2,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `UserLogin_UNIQUE` (`userLogin` ASC),
  UNIQUE INDEX `UserMail_UNIQUE` (`userMail` ASC),
  INDEX `fk_Users_UserRole1_idx` (`userRoleId` ASC),
  CONSTRAINT `fk_Users_UserRole1`
  FOREIGN KEY (`userRoleId`)
  REFERENCES `reverse_auction`.`UserRole` (`idUserRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COMMENT = 'Table for Users System';

-- -----------------------------------------------------
-- Table `reverse_auction`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`Address`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`Address` (
  `idAddress`  INT          NOT NULL AUTO_INCREMENT,
  `country`    VARCHAR(60)  NOT NULL,
  `city`       VARCHAR(100) NOT NULL,
  `postalCode` VARCHAR(30)  NOT NULL,
  `street`     VARCHAR(100) NOT NULL,
  `userId`     INT          NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_Address_Users_idx` (`userId` ASC),
  CONSTRAINT `fk_Address_Users`
  FOREIGN KEY (`userId`)
  REFERENCES `reverse_auction`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COMMENT = 'Users Address Table';

-- -----------------------------------------------------
-- Table `reverse_auction`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`Category`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`Category` (
  `idCategory`          INT         NOT NULL AUTO_INCREMENT,
  `categoryName`        VARCHAR(45) NULL,
  `categoryDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `categoryName_UNIQUE` (`categoryName` ASC)
)
  ENGINE = InnoDB
  COMMENT = 'Category Table';

-- -----------------------------------------------------
-- Table `reverse_auction`.`Subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`Subcategory`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`Subcategory` (
  `idSubcategory`   INT         NOT NULL,
  `subcategoryName` VARCHAR(45) NULL,
  `categoryId`      INT         NOT NULL,
  PRIMARY KEY (`idSubcategory`),
  UNIQUE INDEX `subcategoryName_UNIQUE` (`subcategoryName` ASC),
  INDEX `fk_Subcategory_Category1_idx` (`categoryId` ASC),
  CONSTRAINT `fk_Subcategory_Category1`
  FOREIGN KEY (`categoryId`)
  REFERENCES `reverse_auction`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reverse_auction`.`Offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`Offer`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`Offer` (
  `idOffer`          INT            NOT NULL AUTO_INCREMENT,
  `offerTItle`       VARCHAR(120)   NOT NULL,
  `offerDescription` TEXT           NULL,
  `offerPrice`       DECIMAL(10, 2) NOT NULL,
  `userId`           INT            NOT NULL,
  `auctionId`        INT            NULL,
  `offerAddTIme`     DATETIME       NOT NULL,
  PRIMARY KEY (`idOffer`),
  INDEX `fk_Offer_Users1_idx` (`userId` ASC),
  INDEX `fk_Offer_Auction1_idx` (`auctionId` ASC),
  CONSTRAINT `fk_Offer_Users1`
  FOREIGN KEY (`userId`)
  REFERENCES `reverse_auction`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offer_Auction1`
  FOREIGN KEY (`auctionId`)
  REFERENCES `reverse_auction`.`Auction` (`idAuction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reverse_auction`.`Auction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reverse_auction`.`Auction`;

CREATE TABLE IF NOT EXISTS `reverse_auction`.`Auction` (
  `idAuction`          INT          NOT NULL AUTO_INCREMENT,
  `auctionName`        VARCHAR(100) NOT NULL,
  `auctionDescription` TEXT         NOT NULL,
  `subcategoryId`      INT          NOT NULL,
  `userId`             INT          NOT NULL,
  `auctionStartTime`   DATETIME     NOT NULL,
  `auctionEndTime`     DATETIME     NULL,
  `auctionIsActive`    TINYINT(1)   NULL,
  `auctionView`        INT          NULL,
  `auctionWinOfferID`  INT          NULL,
  PRIMARY KEY (`idAuction`),
  INDEX `fk_Auction_Subcategory1_idx` (`subcategoryId` ASC),
  INDEX `fk_Auction_Users1_idx` (`userId` ASC),
  INDEX `fk_Auction_Offer1_idx` (`auctionWinOfferID` ASC),
  CONSTRAINT `fk_Auction_Subcategory1`
  FOREIGN KEY (`subcategoryId`)
  REFERENCES `reverse_auction`.`Subcategory` (`idSubcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_Users1`
  FOREIGN KEY (`userId`)
  REFERENCES `reverse_auction`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auction_Offer1`
  FOREIGN KEY (`auctionWinOfferID`)
  REFERENCES `reverse_auction`.`Offer` (`idOffer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COMMENT = 'Auction Table';


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`UserRole`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`UserRole` (`idUserRole`, `userRoleName`)
VALUES (1, 'Admin');
INSERT INTO `reverse_auction`.`UserRole` (`idUserRole`, `userRoleName`)
VALUES (2, 'User');

COMMIT;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`User` (`idUser`,
                                      `userLogin`,
                                      `userFirstName`,
                                      `userLastName`,
                                      `userBirth`,
                                      `userMail`,
                                      `userRoleId`)
VALUES (1, 'Nowak01', 'Adam', 'Nowak', '1991-02-18', 'adam.nowak@gmail.com', 2);
INSERT INTO `reverse_auction`.`User` (`idUser`,
                                      `userLogin`,
                                      `userFirstName`,
                                      `userLastName`,
                                      `userBirth`,
                                      `userMail`,
                                      `userRoleId`)
VALUES (2, 'grazyna02', 'Grażyna', 'Kowalska', '1982-03-06', 'grazyna.kowalska@wp.pl', 2);

COMMIT;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`Address`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`Address` (`idAddress`, `country`, `city`, `postalCode`, `street`, `userId`)
VALUES (1, 'Poland', 'Gdańsk', '80-236', 'Zwycięstwa 65b/2', 1);
INSERT INTO `reverse_auction`.`Address` (`idAddress`, `country`, `city`, `postalCode`, `street`, `userId`)
VALUES (2, 'Poland', 'Warszawa', '00-265', 'Jana Pawała II 3g/2', 2);

COMMIT;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`Category` (`idCategory`, `categoryName`, `categoryDescription`)
VALUES (1, 'Elektronika', 'Kategoria z Elektroniką');
INSERT INTO `reverse_auction`.`Category` (`idCategory`, `categoryName`, `categoryDescription`)
VALUES (2, 'Nieruchomości', 'Kategoria z Nieruchomościami');

COMMIT;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`Subcategory`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`Subcategory` (`idSubcategory`, `subcategoryName`, `categoryId`)
VALUES (1, 'Komputery', 1);
INSERT INTO `reverse_auction`.`Subcategory` (`idSubcategory`, `subcategoryName`, `categoryId`)
VALUES (2, 'Telefony', 1);
INSERT INTO `reverse_auction`.`Subcategory` (`idSubcategory`, `subcategoryName`, `categoryId`)
VALUES (3, 'Wynajem', 2);
INSERT INTO `reverse_auction`.`Subcategory` (`idSubcategory`, `subcategoryName`, `categoryId`)
VALUES (4, 'Sprzedam', 2);
INSERT INTO `reverse_auction`.`Subcategory` (`idSubcategory`, `subcategoryName`, `categoryId`)
VALUES (5, 'Kupie', 2);

COMMIT;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`Offer`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`Offer` (`idOffer`,
                                       `offerTItle`,
                                       `offerDescription`,
                                       `offerPrice`,
                                       `userId`,
                                       `auctionId`,
                                       `offerAddTIme`)
VALUES (1, 'Mieszkanie w Radomiu ul.Bytowska', 'Ładne mieszkanie', 256000.00, 1, NULL, '2018-06-05');

COMMIT;

-- -----------------------------------------------------
-- Data for table `reverse_auction`.`Auction`
-- -----------------------------------------------------
START TRANSACTION;
USE `reverse_auction`;
INSERT INTO `reverse_auction`.`Auction` (`idAuction`,
                                         `auctionName`,
                                         `auctionDescription`,
                                         `subcategoryId`,
                                         `userId`,
                                         `auctionStartTime`,
                                         `auctionEndTime`,
                                         `auctionIsActive`,
                                         `auctionView`,
                                         `auctionWinOfferID`)
VALUES (1,
        'Kupie Mieszaknie w Radomiu',
        'Kupie mieszkanie w Radomiu. Najlepiej w pobliżu centrum miasta. Minimum 3 pokoje najlepiej na parterze.',
        5,
        2,
        '2018-05-28',
        '2018-06-28',
        1,
        250,
        NULL);

COMMIT;

